### ISSUE TITLE
make Orcs, Wraiths, and fancy Spiders drop things on death.

### ISSUE THREAD

**Issue by kennyrkun** [kennyrkun/Erostey-Public#1]
currently none of our fancy mobs drop anything, and they should. 

@Auduceus is in charge of this, because MythicMobs are one of the only things he can do.

they should drop:
- experience
- items
   - rare items for rare mobs
   - strong items for strong mobs
      - not "icarus strong"
- maybe money? can discuss if needed.

**Comment by Huntress14086** [comment]
I don't know about money if there also getting items and experience.

**Comment by kennyrkun** [comment]
I was thinking the same thing.

but players were complaining about not having enough ways to make money, since all you could really do was vote. and people didn't want to vote.

**Comment by kennyrkun** [comment]
This no longer applies as MythicalMobs has been removed from the server. In the future, it is possible that the plugin will be reinstalled. In that case, this issue should be reopened.
